# Generated by tools/generate_music_loudness_catalog.py. Do not hand-edit.
class_name MusicLoudnessCatalog
extends RefCounted

const TARGET_INTEGRATED_LUFS := -15.0
const TRUE_PEAK_CEILING_DBFS := -1.0
const MIN_NORMALIZATION_GAIN_DB := -12.0
const MAX_NORMALIZATION_GAIN_DB := 4.0
const DEVICE_REFERENCE_GAIN_DB := 6.5
const TRACK_MEASUREMENTS := {
	"res://assets/sounds/music/Kaiser Wilhelm II - Rede vom 6. August 1914.mp3": Vector2(-20.50, -3.80),
	"res://assets/sounds/music/nich gucken JUNGE.mp3": Vector2(-8.00, 1.80),
	"res://assets/sounds/music/not so legally downloaded music/Deutsch Swing/Die Gedanken sind frei 🎶 altes Deutsches Volkslied.mp3": Vector2(-14.20, -2.20),
	"res://assets/sounds/music/not so legally downloaded music/Deutsch Swing/Es geht alles vorüber es geht alles vorbei.mp3": Vector2(-14.60, -1.30),
	"res://assets/sounds/music/not so legally downloaded music/Deutsch Swing/LALE ANDERSEN, _Lili Marleen_ (1938)..mp3": Vector2(-9.90, 0.40),
	"res://assets/sounds/music/not so legally downloaded music/Deutsch Swing/Liebe Kommt Einmal Von Irgendwo her.mp3": Vector2(-14.20, -0.00),
	"res://assets/sounds/music/not so legally downloaded music/Deutsch Swing/Regentropfen.mp3": Vector2(-17.10, -2.80),
	"res://assets/sounds/music/not so legally downloaded music/Deutsch Swing/Siebenmal In Der Woche - Vico Torriani.mp3": Vector2(-16.60, -3.70),
	"res://assets/sounds/music/not so legally downloaded music/Deutsch Swing/Sing Nachtigall Sing.mp3": Vector2(-15.10, -5.30),
	"res://assets/sounds/music/not so legally downloaded music/Deutsch Swing/Wenn die Sonne Scheint, Annemarie (Die Landpartie) - With Lyrics.mp3": Vector2(-12.90, -0.00),
	"res://assets/sounds/music/not so legally downloaded music/Deutsch Swing/Wilhelm Strienz - Gute Nacht, Mutter!.mp3": Vector2(-20.90, -4.20),
	"res://assets/sounds/music/not so legally downloaded music/NDH/Hahnenkampf.mp3": Vector2(-6.50, 1.70),
	"res://assets/sounds/music/not so legally downloaded music/NDH/Hässlich.mp3": Vector2(-6.60, 2.60),
	"res://assets/sounds/music/not so legally downloaded music/NDH/Kalt.mp3": Vector2(-6.20, 1.70),
	"res://assets/sounds/music/not so legally downloaded music/NDH/Kosmonaut [Official Audio].mp3": Vector2(-7.10, 2.50),
	"res://assets/sounds/music/not so legally downloaded music/NDH/Liebe [Official Audio].mp3": Vector2(-7.10, 2.60),
	"res://assets/sounds/music/not so legally downloaded music/NDH/MEGAHERZ - Vorhang Auf (Official Video).mp3": Vector2(-6.40, 2.10),
	"res://assets/sounds/music/not so legally downloaded music/NDH/Megaherz - Jagdzeit.mp3": Vector2(-7.20, 2.10),
	"res://assets/sounds/music/not so legally downloaded music/NDH/NDH [Official Audio].mp3": Vector2(-7.40, 3.60),
	"res://assets/sounds/music/not so legally downloaded music/NDH/NEBELHAUS - Der Piet am Galgen [Official Video] _ Daemoria Records.mp3": Vector2(-8.30, 1.00),
	"res://assets/sounds/music/not so legally downloaded music/NDH/NEBELHAUS - Wo alle Straßen enden.mp3": Vector2(-9.20, 1.70),
	"res://assets/sounds/music/not so legally downloaded music/NDH/Oomph! - Labyrinth (Videoclip).mp3": Vector2(-13.70, -0.90),
	"res://assets/sounds/music/not so legally downloaded music/NDH/Rammstein - Deutschland.mp3": Vector2(-8.10, 1.40),
	"res://assets/sounds/music/not so legally downloaded music/NDH/Rammstein - Dicke Titten.mp3": Vector2(-8.90, 2.10),
	"res://assets/sounds/music/not so legally downloaded music/NDH/Rammstein - Feuer Frei! (Official Video).mp3": Vector2(-8.00, 1.70),
	"res://assets/sounds/music/not so legally downloaded music/NDH/Thüringer Klöße.mp3": Vector2(-7.40, 1.20),
	"res://assets/sounds/music/not so legally downloaded music/Nachtmahr/Die Straße.mp3": Vector2(-10.60, 0.30),
	"res://assets/sounds/music/not so legally downloaded music/Nachtmahr/Droge_Musik.mp3": Vector2(-10.30, 0.50),
	"res://assets/sounds/music/not so legally downloaded music/Nachtmahr/Gehorsam.mp3": Vector2(-9.00, 1.80),
	"res://assets/sounds/music/not so legally downloaded music/Nachtmahr/Mein Name.mp3": Vector2(-6.70, 1.30),
	"res://assets/sounds/music/not so legally downloaded music/Nachtmahr/NACHTMAHR - Beweg dich! (official video).mp3": Vector2(-17.70, -5.40),
	"res://assets/sounds/music/not so legally downloaded music/Nachtmahr/Nenn mich wie du willst (Remastered).mp3": Vector2(-7.90, 3.50),
	"res://assets/sounds/music/not so legally downloaded music/Nachtmahr/Verräter an Gott.mp3": Vector2(-8.60, 2.10),
	"res://assets/sounds/music/not so legally downloaded music/Nachtmahr/Weil ich's kann (Remastered).mp3": Vector2(-9.30, 1.30),
	"res://assets/sounds/music/not so legally downloaded music/Vor der Runde/And One - Panzermensch.mp3": Vector2(-9.10, 1.80),
	"res://assets/sounds/music/not so legally downloaded music/Vor der Runde/Die Grenzwacht Hielt im Osten (German Folk Song by Freikorps).mp3": Vector2(-9.90, 0.00),
	"res://assets/sounds/music/not so legally downloaded music/Vor der Runde/Die Grenzwacht hielt im Osten __ acoustic German folk song _ Volkslied.mp3": Vector2(-27.20, -8.60),
	"res://assets/sounds/music/not so legally downloaded music/Vor der Runde/Erika (Marching Song of the German Military).mp3": Vector2(-14.50, -2.00),
	"res://assets/sounds/music/not so legally downloaded music/Vor der Runde/Flandern in Not Deutsches Volkslied [+Liedtext].mp3": Vector2(-12.60, 0.00),
	"res://assets/sounds/music/not so legally downloaded music/Vor der Runde/Freigeisterbund - Freikorps voran [German Post War Song][+ English Translation].mp3": Vector2(-7.80, 2.30),
	"res://assets/sounds/music/not so legally downloaded music/Vor der Runde/Freikorps marschiert In fremdes Land (1919) German Freikorps' Counter-Revolutionary Song.mp3": Vector2(-8.70, 1.80),
	"res://assets/sounds/music/not so legally downloaded music/Vor der Runde/Hundert Mann und ein Befehl.mp3": Vector2(-10.90, 0.60),
	"res://assets/sounds/music/not so legally downloaded music/Vor der Runde/Ich bin Soldat, doch bin ich es nicht gerne.mp3": Vector2(-14.70, -0.60),
	"res://assets/sounds/music/not so legally downloaded music/Vor der Runde/Im Wald, Im Grünen Walde + Lyrics.mp3": Vector2(-14.50, -1.20),
	"res://assets/sounds/music/not so legally downloaded music/Vor der Runde/In einem Polenstädtchen.mp3": Vector2(-12.90, -1.20),
	"res://assets/sounds/music/not so legally downloaded music/Vor der Runde/Königin der Waffen Deutsche Infanterie.mp3": Vector2(-8.30, 4.70),
	"res://assets/sounds/music/not so legally downloaded music/Vor der Runde/Lebe wohl, du kleine Monika.mp3": Vector2(-13.40, -0.50),
	"res://assets/sounds/music/not so legally downloaded music/Vor der Runde/Preußens Gloria Beste Version (re upload).mp3": Vector2(-14.20, 0.30),
	"res://assets/sounds/music/not so legally downloaded music/Vor der Runde/Schwarzbraun ist die haselnuss - german song.mp3": Vector2(-14.50, -1.00),
	"res://assets/sounds/music/not so legally downloaded music/Vor der Runde/WOLFNACHT _Die Toten erwachen_ (incl. Lyrics).mp3": Vector2(-6.90, 1.60),
	"res://assets/sounds/music/not so legally downloaded music/Vor der Runde/Was geh'n euch meine Lumpen an • Sad German Song [+GER & ENG Lyrics].mp3": Vector2(-12.00, 0.20),
	"res://assets/sounds/music/not so legally downloaded music/Vor der Runde/Westerwaldlied - [German Marching Song].mp3": Vector2(-8.60, 2.00),
	"res://assets/sounds/music/not so legally downloaded music/Vor der Runde/_Heil dir im Siegerkranz_ (Hail to Thee in Victor's Crown) - Anthem of the German Empire.mp3": Vector2(-10.40, -0.20),
	"res://assets/sounds/music/not so legally downloaded music/Vor der Runde/k. k. Infanterie Marsch _Kärntner Liedermarsch_.mp3": Vector2(-11.10, 0.40),
	"res://assets/sounds/music/not so legally downloaded music/Vor der Runde/„Wir sind des Geyers schwarzer Haufen“ • Soldatenlied [+Liedtext].mp3": Vector2(-10.10, 0.00),
	"res://assets/sounds/music/not so legally downloaded music/Vor der Runde/✠ Auf Kreta bei Sturm und bei Regen- Fallschirmjägerlied ✠ (Accordion + Chorus Version).mp3": Vector2(-11.50, 0.30),
	"res://assets/sounds/music/not so legally downloaded music/Vorwärts/Brutalismus 3000 - Europaträume.mp3": Vector2(-6.30, 2.70),
	"res://assets/sounds/music/not so legally downloaded music/Vorwärts/FAHRERFLUCHT.mp3": Vector2(-3.60, 4.20),
	"res://assets/sounds/music/not so legally downloaded music/Vorwärts/Ich will dich einfach Stampfen sehen!.mp3": Vector2(-4.80, 3.80),
	"res://assets/sounds/music/not so legally downloaded music/Vorwärts/POLTERGST - Feuerzeug & Benzin.mp3": Vector2(-5.40, 3.50),
	"res://assets/sounds/music/not so legally downloaded music/Vorwärts/POLTERGST - Sonne (Official Audio).mp3": Vector2(-5.40, 2.00),
	"res://assets/sounds/music/not so legally downloaded music/Vorwärts/Scheiss Egal (District Red Remix).mp3": Vector2(-4.40, 1.90),
	"res://assets/sounds/music/not so legally downloaded music/Vorwärts/Sturmmann - Schwarzer Rabe.mp3": Vector2(-8.40, 0.70),
	"res://assets/sounds/music/not so legally downloaded music/Vorwärts/Trizto - Es kracht in Buxtehude (feat. MontanaBlack).mp3": Vector2(-8.60, 1.80),
	"res://assets/sounds/music/not so legally downloaded music/Vorwärts/Wir sind des Geyers schwarzer Haufen.mp3": Vector2(-18.50, -4.90),
	"res://assets/sounds/music/not so legally downloaded music/Vorwärts/Zehn kleine Jägermeister.mp3": Vector2(-19.60, -8.60),
	"res://assets/sounds/music/not so legally downloaded music/Vorwärts/Übermensch - Könige Europas.mp3": Vector2(-8.10, 0.20),
	"res://assets/sounds/music/not so legally downloaded music/gothic/Gothic 3 Soundtrack - End Titles.mp3": Vector2(-27.30, -10.20),
	"res://assets/sounds/music/temp/Disposal Unit (Imperium Mix).mp3": Vector2(-11.80, -0.80),
	"res://assets/sounds/music/temp/Immortal Imperium.mp3": Vector2(-9.70, -0.10),
	"res://assets/sounds/music/temp/Imperial Advance.mp3": Vector2(-12.60, -1.10),
	"res://assets/sounds/music/temp/NEBELHAUS - Texas [Official Video] _ Daemoria Records.mp3": Vector2(-6.30, 1.90),
	"res://assets/sounds/music/temp/The Gauntlet.mp3": Vector2(-8.50, 0.90),
	"res://assets/sounds/music/temp/_Ami, Go Home!_ - East German Anti-American Song.mp3": Vector2(-13.30, 0.20),
	"res://assets/sounds/music/temp/amerika.mp3": Vector2(-8.90, 1.50),
}


static func gain_db_for_path(path: String) -> float:
	var measurement: Vector2 = TRACK_MEASUREMENTS.get(path, Vector2(INF, INF))
	if not measurement.is_finite():
		return 0.0
	var loudness_gain := TARGET_INTEGRATED_LUFS - measurement.x
	var peak_safe_gain := TRUE_PEAK_CEILING_DBFS - measurement.y
	return clampf(
		minf(loudness_gain, peak_safe_gain),
		MIN_NORMALIZATION_GAIN_DB,
		MAX_NORMALIZATION_GAIN_DB
	)


static func normalized_integrated_lufs(path: String) -> float:
	var measurement: Vector2 = TRACK_MEASUREMENTS.get(path, Vector2(INF, INF))
	if not measurement.is_finite():
		return INF
	return measurement.x + gain_db_for_path(path)


static func emitted_reference_lufs(path: String) -> float:
	var normalized := normalized_integrated_lufs(path)
	return normalized + DEVICE_REFERENCE_GAIN_DB if is_finite(normalized) else INF
