class_name SdfInteriorSurfaceBuilder
extends RefCounted

## Extracts only newly exposed interior faces from the production sparse-SDF contour. This is the
## reusable bridge for animated/destructible actors: their imported skinned shell is aperture-clipped,
## while every visible wound wall is still generated by the exact world-destruction mesher.


static func build(
	field: SparseSdfVolumeData,
	profile: DestructionTextureDefinition
) -> Dictionary:
	if field == null or profile == null:
		return {"mesh": null, "vertices": PackedVector3Array(), "indices": PackedInt32Array()}
	var vertices := PackedVector3Array()
	var normals := PackedVector3Array()
	var colors := PackedColorArray()
	var indices := PackedInt32Array()
	for z: int in range(field.brick_counts.z):
		for y: int in range(field.brick_counts.y):
			for x: int in range(field.brick_counts.x):
				_append_chunk_interior(
					field,
					profile,
					Vector3i(x, y, z),
					vertices,
					normals,
					colors,
					indices
				)
	if indices.is_empty():
		return {
			"mesh": null,
			"vertices": vertices,
			"normals": normals,
			"colors": colors,
			"indices": indices,
			"triangle_count": 0,
		}
	var arrays := []
	arrays.resize(Mesh.ARRAY_MAX)
	arrays[Mesh.ARRAY_VERTEX] = vertices
	arrays[Mesh.ARRAY_NORMAL] = normals
	arrays[Mesh.ARRAY_COLOR] = colors
	arrays[Mesh.ARRAY_INDEX] = indices
	var mesh := ArrayMesh.new()
	mesh.add_surface_from_arrays(Mesh.PRIMITIVE_TRIANGLES, arrays)
	return {
		"mesh": mesh,
		"vertices": vertices,
		"normals": normals,
		"colors": colors,
		"indices": indices,
		"triangle_count": indices.size() / 3,
	}


static func build_chunk(
	field: SparseSdfVolumeData,
	profile: DestructionTextureDefinition,
	coordinate: Vector3i,
	prepared_contour: Dictionary = {}
) -> Dictionary:
	## Filter one already-contoured chunk down to newly exposed material. The expensive contour can
	## therefore run on WorkerThreadPool while ArrayMesh creation remains on the main thread.
	if field == null or profile == null or not field.brick_is_valid(coordinate):
		return {"mesh": null, "vertices": PackedVector3Array(), "indices": PackedInt32Array()}
	var vertices := PackedVector3Array()
	var normals := PackedVector3Array()
	var colors := PackedColorArray()
	var indices := PackedInt32Array()
	var contour := (
		prepared_contour
		if not prepared_contour.is_empty()
		else SdfDualContouringMesher.build_chunk(field, coordinate)
	)
	_append_contour_interior(
		field,
		profile,
		contour,
		vertices,
		normals,
		colors,
		indices
	)
	var mesh: ArrayMesh
	if not indices.is_empty():
		var arrays := []
		arrays.resize(Mesh.ARRAY_MAX)
		arrays[Mesh.ARRAY_VERTEX] = vertices
		arrays[Mesh.ARRAY_NORMAL] = normals
		arrays[Mesh.ARRAY_COLOR] = colors
		arrays[Mesh.ARRAY_INDEX] = indices
		mesh = ArrayMesh.new()
		mesh.add_surface_from_arrays(Mesh.PRIMITIVE_TRIANGLES, arrays)
	return {
		"mesh": mesh,
		"vertices": vertices,
		"normals": normals,
		"colors": colors,
		"indices": indices,
		"triangle_count": indices.size() / 3,
	}


static func _append_chunk_interior(
	field: SparseSdfVolumeData,
	profile: DestructionTextureDefinition,
	coordinate: Vector3i,
	vertices: PackedVector3Array,
	normals: PackedVector3Array,
	colors: PackedColorArray,
	indices: PackedInt32Array
) -> void:
	var result := SdfDualContouringMesher.build_chunk(field, coordinate)
	_append_contour_interior(field, profile, result, vertices, normals, colors, indices)


static func _append_contour_interior(
	field: SparseSdfVolumeData,
	profile: DestructionTextureDefinition,
	result: Dictionary,
	vertices: PackedVector3Array,
	normals: PackedVector3Array,
	colors: PackedColorArray,
	indices: PackedInt32Array
) -> void:
	if bool(result.get("empty", true)):
		return
	SdfDualContouringMesher.split_box_reference_surface_classes(result)
	var source_vertices: PackedVector3Array = result.get("vertices", PackedVector3Array())
	var source_normals: PackedVector3Array = result.get("normals", PackedVector3Array())
	var source_indices: PackedInt32Array = result.get("indices", PackedInt32Array())
	var surface_classes: PackedByteArray = result.get("surface_classes", PackedByteArray())
	if (
		source_vertices.is_empty()
		or source_normals.size() != source_vertices.size()
		or surface_classes.size() != source_vertices.size()
		or source_indices.size() % 3 != 0
	):
		return
	var remap := PackedInt32Array()
	remap.resize(source_vertices.size())
	remap.fill(-1)
	for triangle_offset: int in range(0, source_indices.size(), 3):
		var first := source_indices[triangle_offset]
		var second := source_indices[triangle_offset + 1]
		var third := source_indices[triangle_offset + 2]
		# split_box_reference_surface_classes duplicates rim vertices by polygon class, so testing one
		# corner is sufficient and cannot tear a mixed exterior/interior triangle.
		if surface_classes[first] != 1:
			continue
		for corner_offset: int in range(3):
			var source_index := source_indices[triangle_offset + corner_offset]
			var destination_index := remap[source_index]
			if destination_index < 0:
				destination_index = vertices.size()
				remap[source_index] = destination_index
				vertices.append(source_vertices[source_index])
				normals.append(source_normals[source_index])
				colors.append(_tissue_color(field, profile, source_vertices[source_index]))
			indices.append(destination_index)


static func _tissue_color(
	field: SparseSdfVolumeData,
	profile: DestructionTextureDefinition,
	position: Vector3
) -> Color:
	var depth := maxf(-field.base_distance(position), field.voxel_size * 0.5)
	var weight := (
		clampf(depth / profile.interior_color_depth, 0.0, 1.0)
		if profile.interior_color_depth > 0.000001
		else 0.0
	)
	return profile.interior_color.lerp(profile.deep_interior_color, weight)
