#!/usr/bin/env python3
"""Bake loudness mastering data and compact source-level visual envelopes for music."""

from __future__ import annotations

import argparse
import array
import concurrent.futures
import math
import pathlib
import re
import subprocess
import sys


SUPPORTED_EXTENSIONS = {".mp3", ".ogg", ".wav"}
INTEGRATED_PATTERN = re.compile(r"I:\s*([-+]?\d+(?:\.\d+)?)\s+LUFS")
TRUE_PEAK_PATTERN = re.compile(r"Peak:\s*([-+]?\d+(?:\.\d+)?)\s+dBFS")
VISUAL_SAMPLE_RATE = 4000
VISUAL_ENVELOPE_HZ = 20
VISUAL_WINDOW_SAMPLES = VISUAL_SAMPLE_RATE // VISUAL_ENVELOPE_HZ
VISUAL_MIN_DYNAMIC_RANGE_DB = 6.0
VISUAL_SILENCE_DB = -72.0


def percentile(sorted_values: list[float], ratio: float) -> float:
	if not sorted_values:
		return VISUAL_SILENCE_DB
	position = min(max(ratio, 0.0), 1.0) * (len(sorted_values) - 1)
	lower = int(math.floor(position))
	upper = min(lower + 1, len(sorted_values) - 1)
	weight = position - lower
	return sorted_values[lower] * (1.0 - weight) + sorted_values[upper] * weight


def measure_visual_envelope(path: pathlib.Path) -> bytes:
	completed = subprocess.run(
		[
			"ffmpeg",
			"-hide_banner",
			"-nostats",
			"-loglevel",
			"error",
			"-i",
			str(path),
			"-vn",
			"-ac",
			"1",
			"-ar",
			str(VISUAL_SAMPLE_RATE),
			"-f",
			"f32le",
			"-",
		],
		capture_output=True,
		check=True,
	)
	samples = array.array("f")
	samples.frombytes(completed.stdout)
	if sys.byteorder != "little":
		samples.byteswap()
	window_db: list[float] = []
	for start in range(0, len(samples), VISUAL_WINDOW_SAMPLES):
		window = samples[start:start + VISUAL_WINDOW_SAMPLES]
		if not window:
			break
		mean_square = sum(sample * sample for sample in window) / len(window)
		window_db.append(10.0 * math.log10(max(mean_square, 1.0e-12)))
	if not window_db:
		return bytes([0])
	active_levels = sorted(value for value in window_db if value > VISUAL_SILENCE_DB)
	if not active_levels:
		return bytes(len(window_db))
	low_db = percentile(active_levels, 0.15)
	high_db = percentile(active_levels, 0.95)
	dynamic_range_db = max(high_db - low_db, VISUAL_MIN_DYNAMIC_RANGE_DB)
	visual_floor_db = high_db - dynamic_range_db
	return bytes(
		round(
			min(max((value - visual_floor_db) / dynamic_range_db, 0.0), 1.0)
			* 255.0
		)
		for value in window_db
	)


def measure(path: pathlib.Path) -> tuple[pathlib.Path, float, float, bytes]:
	completed = subprocess.run(
		[
			"ffmpeg",
			"-hide_banner",
			"-nostats",
			"-loglevel",
			"info",
			"-i",
			str(path),
			"-filter_complex",
			"ebur128=peak=true:framelog=verbose",
			"-f",
			"null",
			"-",
		],
		capture_output=True,
		text=True,
		check=True,
	)
	output = completed.stdout + completed.stderr
	integrated_matches = INTEGRATED_PATTERN.findall(output)
	peak_matches = TRUE_PEAK_PATTERN.findall(output)
	if not integrated_matches or not peak_matches:
		raise RuntimeError(f"ffmpeg did not report EBU R128 values for {path}")
	return (
		path,
		float(integrated_matches[-1]),
		float(peak_matches[-1]),
		measure_visual_envelope(path),
	)


def gdscript_string(value: str) -> str:
	return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main() -> None:
	parser = argparse.ArgumentParser()
	parser.add_argument("--project", type=pathlib.Path, default=pathlib.Path.cwd())
	parser.add_argument("--workers", type=int, default=4)
	args = parser.parse_args()
	project = args.project.resolve()
	music_root = project / "assets" / "sounds" / "music"
	paths = sorted(
		path
		for path in music_root.rglob("*")
		if path.is_file() and path.suffix.lower() in SUPPORTED_EXTENSIONS
	)
	measurements: list[tuple[pathlib.Path, float, float, bytes]] = []
	with concurrent.futures.ThreadPoolExecutor(max_workers=max(args.workers, 1)) as pool:
		for result in pool.map(measure, paths):
			measurements.append(result)

	lines = [
		"# Generated by tools/generate_music_loudness_catalog.py. Do not hand-edit.",
		"class_name MusicLoudnessCatalog",
		"extends RefCounted",
		"",
		"const TARGET_INTEGRATED_LUFS := -15.0",
		"const TRUE_PEAK_CEILING_DBFS := -1.0",
		"const MIN_NORMALIZATION_GAIN_DB := -12.0",
		"const MAX_NORMALIZATION_GAIN_DB := 4.0",
		"const DEVICE_REFERENCE_GAIN_DB := 6.5",
		"const TRACK_MEASUREMENTS := {",
	]
	for path, integrated_lufs, true_peak_dbfs, _envelope in measurements:
		resource_path = "res://" + path.relative_to(project).as_posix()
		lines.append(
			f"\t{gdscript_string(resource_path)}: "
			f"Vector2({integrated_lufs:.2f}, {true_peak_dbfs:.2f}),"
		)
	lines.extend(
		[
			"}",
			"",
			"",
			"static func gain_db_for_path(path: String) -> float:",
			"\tvar measurement: Vector2 = TRACK_MEASUREMENTS.get(path, Vector2(INF, INF))",
			"\tif not measurement.is_finite():",
			"\t\treturn 0.0",
			"\tvar loudness_gain := TARGET_INTEGRATED_LUFS - measurement.x",
			"\tvar peak_safe_gain := TRUE_PEAK_CEILING_DBFS - measurement.y",
			"\treturn clampf(",
			"\t\tminf(loudness_gain, peak_safe_gain),",
			"\t\tMIN_NORMALIZATION_GAIN_DB,",
			"\t\tMAX_NORMALIZATION_GAIN_DB",
			"\t)",
			"",
			"",
			"static func normalized_integrated_lufs(path: String) -> float:",
			"\tvar measurement: Vector2 = TRACK_MEASUREMENTS.get(path, Vector2(INF, INF))",
			"\tif not measurement.is_finite():",
			"\t\treturn INF",
			"\treturn measurement.x + gain_db_for_path(path)",
			"",
			"",
			"static func emitted_reference_lufs(path: String) -> float:",
			"\tvar normalized := normalized_integrated_lufs(path)",
			"\treturn normalized + DEVICE_REFERENCE_GAIN_DB if is_finite(normalized) else INF",
			"",
		]
	)
	output_path = project / "scripts" / "audio" / "music_loudness_catalog.gd"
	output_path.write_text("\n".join(lines), encoding="utf-8")

	visual_lines = [
		"# Generated by tools/generate_music_loudness_catalog.py. Do not hand-edit.",
		"class_name MusicVisualEnvelopeCatalog",
		"extends RefCounted",
		"",
		f"const SAMPLE_RATE_HZ := {float(VISUAL_ENVELOPE_HZ):.1f}",
		"static var TRACK_ENVELOPES := {",
	]
	for path, _integrated_lufs, _true_peak_dbfs, envelope in measurements:
		resource_path = "res://" + path.relative_to(project).as_posix()
		visual_lines.append(f"\t{gdscript_string(resource_path)}: PackedByteArray([")
		for start in range(0, len(envelope), 64):
			chunk = envelope[start:start + 64]
			visual_lines.append("\t\t" + ", ".join(str(value) for value in chunk) + ",")
		visual_lines.append("\t]),")
	visual_lines.extend(
		[
			"}",
			"",
			"",
			"static func has_envelope(path: String) -> bool:",
			"\treturn TRACK_ENVELOPES.has(path)",
			"",
			"",
			"static func sample_level(path: String, playback_seconds: float) -> float:",
			"\tif not TRACK_ENVELOPES.has(path):",
			"\t\treturn -1.0",
			"\tvar envelope: PackedByteArray = TRACK_ENVELOPES[path]",
			"\tif envelope.is_empty():",
			"\t\treturn -1.0",
			"\tvar sample_position := clampf(",
			"\t\tmaxf(playback_seconds, 0.0) * SAMPLE_RATE_HZ,",
			"\t\t0.0,",
			"\t\tfloat(envelope.size() - 1)",
			"\t)",
			"\tvar first_index := floori(sample_position)",
			"\tvar second_index := mini(first_index + 1, envelope.size() - 1)",
			"\treturn lerpf(",
			"\t\tfloat(envelope[first_index]) / 255.0,",
			"\t\tfloat(envelope[second_index]) / 255.0,",
			"\t\tsample_position - float(first_index)",
			"\t)",
			"",
		]
	)
	visual_output_path = project / "scripts" / "audio" / "music_visual_envelope_catalog.gd"
	visual_output_path.write_text("\n".join(visual_lines), encoding="utf-8")
	print(
		f"Wrote {len(measurements)} tracks to {output_path} and {visual_output_path}"
	)


if __name__ == "__main__":
	main()
